version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
    labels:
      - "internal"
      - "dependencies"
      - "github_actions"
    groups:
      github-actions:
        patterns:
          - "*"
  # Python
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
    groups:
      python-packages:
        dependency-type: "development"
        patterns:
          - "*"
  # pre-commit
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
    labels:
      - "internal"
      - "dependencies"
      - "pre-commit"
    groups:
      pre-commit:
        patterns:
          - "*"
