docs:
  - changed-files:
    - any-glob-to-any-file:
      - docs/en/docs/**/*
      - docs_src/**/*

lang-all:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - docs/*/docs/**/*
      - all-globs-to-all-files:
        - '!docs/en/docs/**/*'

internal:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**/*
      - scripts/**/*
      - .gitignore
      - .pre-commit-config.yaml
      - pdm_build.py
      - requirements*.txt
