name: Pull Request Labeler
on:
  pull_request_target:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
