name: Pull Request Labeler
on:
  pull_request_target:
  # TODO: remove this
  pull_request:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
