name: Run Export Tests

on:
  push:
	branches: [master, feature/**]
  pull_request:
	branches: [master]

jobs:
  test:
	runs-on: ubuntu-latest

	strategy:
  	matrix:
    	python-version: ["3.10"]

	steps:
	- name: Checkout repo
  	uses: actions/checkout@v4

	- name: Set up Python
  	uses: actions/setup-python@v5
  	with:
    	python-version: ${{ matrix.python-version }}

	- name: Install dependencies
  	run: |
    	python -m pip install --upgrade pip
    	pip install pytest pytest-asyncio httpx pandas xlsxwriter pyarrow reportlab avro-python3 mysql-connector-python protobuf

	- name: Run tests
  	run: |
    	pytest tests/


